export const ApiConstants = {
  MERCADOPAGO_PUBLIC_KEY: import.meta.env.VITE_MERCADOPAGO_PUBLIC_KEY,
  MERCADOPAGO_ACCESS_TOKEN: import.meta.env.VITE_MERCADOPAGO_ACCESS_TOKEN,
  FIREBASE_STORAGE_TOKEN: import.meta.env.VITE_FIREBASE_STORAGE_TOKEN,
  PDF_CONVERTER_API_URL: import.meta.env.VITE_PDF_CONVERTER_API_URL,
};
